GET http://localhost:3001/api/persons/4
### bad delete
DELETE http://localhost:3001/api/persons/5
### good delete
DELETE http://localhost:3001/api/persons/6785a23fa49e9c15be2ac4cc
### good post
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Bastiancitadaadao",
    "number": "+56 9xxxxxx"
}
### name messing 
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "+56 9xxxxxx"
}
### number messing 
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Bastiancito"
}
###
GET http://localhost:3001/api/persons/6782df370c6d591c80b3ec57
###
GET http://localhost:3001/info
